url: 'https://borland.ml'

collections:
    codelab:
        output: true
        label: 'Codelab'
        # permalink: /codelab/:collection/:path

plugins:
  - jekyll-sitemap

exclude:
  - README.md
