---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: layout
  type: text
  config:
    required: false
  label: Layout
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- test.md
- _arduino/modules/test-module.md
