---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: layout
  type: text
  config:
    required: false
  label: Layout
- name: categories
  type: tag_list
  default: []
  label: Categories
pages:
- test.md
